# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: root
  timeout: 5000


development:

  <<: *default

  database: article11 

test:

  <<: *default

  database: article11 



production:

  <<: *default

  database: article11 
